### ISSUE TITLE
suma resta 

### ISSUE THREAD

**Issue by mae18-25** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-mae18-25#1]
[ejercicios de suma resta.pdf](https://github.com/user-attachments/files/16861006/ejercicios.de.suma.resta.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:21/25
Figuras, ilustraciones y fotografías :25/25
Resultados y conclusiones:23/25
Calificación final:18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
